import type { Metadata } from "next";
import { Cinzel, Josefin_Sans } from "next/font/google";
import "./globals.css";

const josefinsans = Josefin_Sans({
  subsets:['latin']
})

const cinzel = Cinzel({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${cinzel.className} ${josefinsans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
